weighted loss
kr-colab/locator pull request #21
Opened 2020-11-06 21:58 UTC by clararehmann

adding an option to weight the loss function to 10^-N where N is the number of samples at a unique location

2020-11-06 23:00 UTC, andrewkern commented on scripts/locator.py
> +            sample_weights.append(10 ** -(loc_dict[(round(sample_data.loc[i, 'x']), round(sample_data.loc[i, 'y']))]))
wondering why this is the weight @clararehmann? why not 1/n?

2020-11-06 23:07 UTC, cjbattey commented on scripts/locator.py
> +            if np.isnan(sample_data.loc[i, 'x']) != True:
easier to read as `if not np.isnan(...)`

2020-11-06 23:07 UTC, cjbattey commented on scripts/locator.py
> +        if np.isnan(sample_data.loc[i, 'x']) != True and i not in test:
here too

2020-11-06 23:08 UTC, cjbattey commented on scripts/locator.py
> +        if args.weight_samples == True:
don't need the `==True`

2020-11-06 23:12 UTC, cjbattey commented on scripts/locator.py
> +parser.add_argument('--weight_samples',default=False,type=bool,help='normalize sample loss across space (for uneven location sampling)')
Let's set this up like the other boolean arguments: 
`parser.add_argument("--weight_samples",default=False,action="store_true",
                    help="normalize sample loss across space to account for uneven location sampling.")`
Then `args.weight_samples` evaluates to `False` unless `--weight_samples` is included in the command.

2020-11-06 23:18 UTC, cjbattey requested changes
This looks super cool! I left some comments for minor code changes, but I also want to see some sort of validation tests before we merge to master. Can you show me some output for this? I can zoom evenings or most of the day on Tuesdays and Fridays if it's easier in person. We should probably draft a section in the readme to explain the option too.

2020-11-19 03:24 UTC, cjbattey approved these changes
looks good to me.

2021-03-29 23:53 UTC, cjbattey commented
Realized this never got merged -- sorry about that. Are we still happy with this implementation @clararehmann? Any objections to merging now?

2023-06-26 20:58 UTC, closed without merging